# Generated by Django 4.2.7 on 2023-11-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_mobile', models.CharField(max_length=20)),
                ('table_number', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time', models.IntegerField(choices=[(300, '3:00 PM'), (330, '3:30 PM'), (400, '4:00 PM'), (430, '4:30 PM'), (500, '5:00 PM'), (530, '5:30 PM'), (600, '6:00 PM'), (630, '6:30 PM'), (700, '7:00 PM'), (730, '7:30 PM'), (800, '8:00 PM'), (830, '8:30 PM'), (900, '9:00 PM'), (930, '9:30 PM')])),
                ('party_number', models.PositiveIntegerField()),
                ('dietary_requirements', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
